create header+navbar and added test (missing logo)
oneplan-project/oneplan-ui pull request #2
Opened 2021-08-19 06:11 UTC by Oatsty

2021-08-19 12:30 UTC, enwee1998 requested changes
looks good just few changes

2021-08-19 12:30 UTC, enwee1998 commented on src/styles/header.scss
> +@import url("https://fonts.googleapis.com/css2?family=Prompt");
can remove this import since we will import them in a global style later

2021-08-19 12:30 UTC, enwee1998 commented on src/styles/header.scss
> +.layout {
all css class should be prefixed with component name avoiding name collision e.g. **`.navbar-latout`** unless they are a common css class

2021-08-19 12:30 UTC, enwee1998 commented on src/components/header.tsx
> +const TopHeader: React.FC<Props> = ({
File name should be `Topheader.component.tsx` too

2021-08-19 12:30 UTC, enwee1998 commented on src/pages/Home.tsx
> +      <TopHeader homeClick={e => {}} contactClick={e => {}} createClick={e => {}} logInClick={e => {}} search={e => {}}/>
Better place this in App.tsx since we will use this throughout a whole website

2021-08-19 12:30 UTC, enwee1998 commented on src/components/header.tsx
> +}
personally not sure about passing some of these functions through props but i'm ok with this or maybe custom hooks for this component

2021-08-22 01:35 UTC, mdechdee commented on package.json
> +    "reactstrap": "^8.9.0",
do we need `reactstrap`? i think we should stick to one component library `antd`

2021-08-22 01:35 UTC, mdechdee commented on src/test/header.test.tsx
> +  expect(search).toHaveBeenCalledTimes(1);
this test is too tedious, might need to extract only core logic to test
it will be hard to maintain and review

2021-08-22 01:35 UTC, mdechdee commented on src/styles/header.scss
> +    font-family: Prompt;
might need to use variable / global style

2021-08-22 01:35 UTC, mdechdee commented on src/components/header.tsx
> +}
i think they shouldn't be passed as props since this component is highly ordered, maybe just implement the function directly in the file

2021-08-22 01:35 UTC, mdechdee commented on src/components/header.tsx
> +          <LineOutlined style={{ width: "100px", fontSize: "72px" }} />
should not define style in `.tsx` file, just put it in `header.scss`

2021-08-22 01:35 UTC, mdechdee commented on src/components/header.tsx
> +export default TopHeader;
should separate `TopHeader.tsx` to  `Header.tsx` and `TopNav.tsx`

2021-09-14 17:00 UTC, closed without merging